-- Eliminar base de datos si existe y crearla nueva
DROP DATABASE IF EXISTS dbsiaade;
CREATE DATABASE dbsiaade;

-- Conectar a la nueva base de datos
\c dbsiaade;

-- Habilitar extensiones necesarias
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =====================================================
-- TABLAS PRINCIPALES
-- =====================================================

-- Tabla de roles
DROP TABLE IF EXISTS roles CASCADE;
CREATE TABLE roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

-- Tabla de datos de dirección
DROP TABLE IF EXISTS address_data CASCADE;
CREATE TABLE address_data (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street TEXT,
    number TEXT,
    floor TEXT,
    apartment TEXT,
    neighborhood TEXT,
    locality TEXT,
    province TEXT,
    postal_code TEXT,
    country TEXT
);

-- Tabla principal de usuarios
DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT,
    last_name TEXT,
    email TEXT UNIQUE,
    password TEXT,
    cuil TEXT UNIQUE,
    role_id INTEGER NOT NULL REFERENCES roles(id) ON DELETE RESTRICT
);

-- Tabla de información adicional del usuario
DROP TABLE IF EXISTS user_info CASCADE;
CREATE TABLE user_info (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    document_type TEXT,
    document_value TEXT,
    phone TEXT,
    emergency_name TEXT,
    emergency_phone TEXT
);

-- Tabla de datos comunes (personales)
DROP TABLE IF EXISTS common_data CASCADE;
CREATE TABLE common_data (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    address_data_id INTEGER REFERENCES address_data(id) ON DELETE SET NULL,
    sex TEXT,
    birth_date DATE,
    birth_place TEXT,
    nationality TEXT
);

-- =====================================================
-- TABLAS DE ROLES ESPECÍFICOS
-- =====================================================

-- Tabla de estudiantes
DROP TABLE IF EXISTS students CASCADE;
CREATE TABLE students (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    legajo TEXT UNIQUE
);

-- Tabla de profesores
DROP TABLE IF EXISTS teachers CASCADE;
CREATE TABLE teachers (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE
);

-- Tabla de preceptores
DROP TABLE IF EXISTS preceptors CASCADE;
CREATE TABLE preceptors (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE
);

-- Tabla de secretarios
DROP TABLE IF EXISTS secretaries CASCADE;
CREATE TABLE secretaries (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    is_directive BOOLEAN DEFAULT false
);

-- =====================================================
-- TABLAS ACADÉMICAS
-- =====================================================

-- Tabla de materias/asignaturas
DROP TABLE IF EXISTS subjects CASCADE;
CREATE TABLE subjects (
    id SERIAL PRIMARY KEY,
    subject_name TEXT,
    teacher UUID NOT NULL REFERENCES teachers(user_id) ON DELETE RESTRICT,
    preceptor UUID NOT NULL REFERENCES preceptors(user_id) ON DELETE RESTRICT,
    course_num INTEGER,
    course_letter TEXT,
    course_year TEXT,
    correlative INTEGER REFERENCES subjects(id) ON DELETE SET NULL
);

-- Tabla de estudiantes por materia (inscripciones)
DROP TABLE IF EXISTS subject_students CASCADE;
CREATE TABLE subject_students (
    id SERIAL PRIMARY KEY,
    subject_id INTEGER NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
    student_id UUID NOT NULL REFERENCES students(user_id) ON DELETE CASCADE,
    enrollment_date DATE
);

-- Tabla de exámenes por materia
DROP TABLE IF EXISTS exams CASCADE;
CREATE TABLE exams (
    id SERIAL PRIMARY KEY,
    subject_id INTEGER NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
    title TEXT, -- Examen 1, Examen parcial, etc.
    date DATE,
    is_valid BOOLEAN -- false = examen que tiene recuperatorio y no debe contarse en el promedio general
);

-- Tabla de resultados de exámenes
DROP TABLE IF EXISTS exam_results CASCADE;
CREATE TABLE exam_results (
    id SERIAL PRIMARY KEY,
    exam_id INTEGER NOT NULL REFERENCES exams(id) ON DELETE CASCADE,
    student_id UUID NOT NULL REFERENCES students(user_id) ON DELETE CASCADE,
    score DECIMAL(4,2) -- Nota obtenida
);

-- =====================================================
-- SISTEMA DE MESAS DE EXÁMENES FINALES
-- =====================================================

-- Tabla de mesas de examen
DROP TABLE IF EXISTS exam_table CASCADE;
CREATE TABLE exam_table (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL, -- Ej: "Mesa de examen diciembre 2025"
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    created_by UUID NOT NULL REFERENCES secretaries(user_id) ON DELETE RESTRICT -- Quién creó la mesa
);

-- Tabla de exámenes finales dentro de cada mesa
DROP TABLE IF EXISTS final_exams CASCADE;
CREATE TABLE final_exams (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_table_id INTEGER NOT NULL REFERENCES exam_table(id) ON DELETE CASCADE,
    subject_id INTEGER NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
    exam_date DATE NOT NULL,
    aula TEXT
);

-- Tabla de inscripciones de estudiantes a exámenes finales
DROP TABLE IF EXISTS final_exams_students CASCADE;
CREATE TABLE final_exams_students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    final_exams_id INTEGER NOT NULL REFERENCES final_exams(id) ON DELETE CASCADE,
    student_id UUID NOT NULL REFERENCES students(user_id) ON DELETE CASCADE,
    enrolled BOOLEAN,
    enrolled_at DATE,
    score DECIMAL(4,2),
    notes TEXT -- Observaciones o comentarios del acta
);


-- =====================================================
-- ÍNDICES PARA OPTIMIZACIÓN
-- =====================================================

-- Índices para búsquedas frecuentes
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_cuil ON users(cuil);
CREATE INDEX idx_users_role_id ON users(role_id);
CREATE INDEX idx_students_legajo ON students(legajo);
CREATE INDEX idx_subjects_teacher ON subjects(teacher);
CREATE INDEX idx_subjects_preceptor ON subjects(preceptor);
CREATE INDEX idx_subjects_correlative ON subjects(correlative);
CREATE INDEX idx_subject_students_subject_id ON subject_students(subject_id);
CREATE INDEX idx_subject_students_student_id ON subject_students(student_id);
CREATE INDEX idx_exams_subject_id ON exams(subject_id);
CREATE INDEX idx_exams_date ON exams(date);
CREATE INDEX idx_exam_results_exam_id ON exam_results(exam_id);
CREATE INDEX idx_exam_results_student_id ON exam_results(student_id);
CREATE INDEX idx_final_exams_exam_table_id ON final_exams(exam_table_id);
CREATE INDEX idx_final_exams_subject_id ON final_exams(subject_id);
CREATE INDEX idx_final_exams_students_final_exam_id ON final_exams_students(final_exams_id);
CREATE INDEX idx_final_exams_students_student_id ON final_exams_students(student_id);

-- =====================================================
-- DATOS INICIALES
-- =====================================================

-- Insertar roles básicos
INSERT INTO roles (name) VALUES 
    ('Administrador'),
    ('Estudiante'),
    ('Profesor'),
    ('Preceptor'),
    ('Secretario');

-- Insertar dirección de ejemplo
INSERT INTO address_data (street, number, floor, apartment, neighborhood, locality, province, postal_code, country)
VALUES ('Av. Libertador', '1234', '3', 'C', 'Palermo', 'Buenos Aires', 'Buenos Aires', '1414', 'Argentina');

-- Insertar usuario administrador por defecto
WITH new_admin_role AS (
    SELECT id FROM roles WHERE name = 'Administrador' LIMIT 1
),
new_address AS (
    SELECT id FROM address_data LIMIT 1
),
new_user AS (
    INSERT INTO users (name, last_name, email, password, cuil, role_id)
    SELECT 'Juan', 'Pérez', 'admin@siaade.edu.ar', '$2b$10$hashdeejemplo', '20-12345678-9', r.id
    FROM new_admin_role r
    RETURNING id
),
user_info_insert AS (
    INSERT INTO user_info (user_id, document_type, document_value, phone, emergency_name, emergency_phone)
    SELECT u.id, 'DNI', '12345678', '01123456789', 'Ana Pérez', '01198765432'
    FROM new_user u
    RETURNING user_id
)
INSERT INTO common_data (user_id, address_data_id, sex, birth_date, birth_place, nationality)
SELECT ui.user_id, a.id, 'Masculino', '1985-06-15', 'Buenos Aires', 'Argentina'
FROM user_info_insert ui, new_address a;

-- Crear usuario secretario de ejemplo
WITH secretary_role AS (
    SELECT id FROM roles WHERE name = 'Secretario' LIMIT 1
),
new_secretary_user AS (
    INSERT INTO users (name, last_name, email, password, cuil, role_id)
    SELECT 'María', 'González', 'secretaria@siaade.edu.ar', '$2b$10$hashdeejemplo2', '27-87654321-4', r.id
    FROM secretary_role r
    RETURNING id
)
INSERT INTO secretaries (user_id, is_directive)
SELECT u.id, true
FROM new_secretary_user u;

-- Crear profesor de ejemplo
WITH teacher_role AS (
    SELECT id FROM roles WHERE name = 'Profesor' LIMIT 1
),
new_teacher_user AS (
    INSERT INTO users (name, last_name, email, password, cuil, role_id)
    SELECT 'Carlos', 'Rodríguez', 'profesor@siaade.edu.ar', '$2b$10$hashdeejemplo3', '20-11223344-5', r.id
    FROM teacher_role r
    RETURNING id
)
INSERT INTO teachers (user_id)
SELECT u.id
FROM new_teacher_user u;

-- Crear preceptor de ejemplo
WITH preceptor_role AS (
    SELECT id FROM roles WHERE name = 'Preceptor' LIMIT 1
),
new_preceptor_user AS (
    INSERT INTO users (name, last_name, email, password, cuil, role_id)
    SELECT 'Ana', 'Martínez', 'preceptor@siaade.edu.ar', '$2b$10$hashdeejemplo4', '27-55667788-9', r.id
    FROM preceptor_role r
    RETURNING id
)
INSERT INTO preceptors (user_id)
SELECT u.id
FROM new_preceptor_user u;

-- Crear estudiante de ejemplo
WITH student_role AS (
    SELECT id FROM roles WHERE name = 'Estudiante' LIMIT 1
),
new_student_user AS (
    INSERT INTO users (name, last_name, email, password, cuil, role_id)
    SELECT 'Luis', 'López', 'estudiante@siaade.edu.ar', '$2b$10$hashdeejemplo5', '20-99887766-3', r.id
    FROM student_role r
    RETURNING id
)
INSERT INTO students (user_id, legajo)
SELECT u.id, 'E12345'
FROM new_student_user u;

-- Insertar materias de ejemplo
WITH teacher_id AS (
    SELECT user_id FROM teachers LIMIT 1
),
preceptor_id AS (
    SELECT user_id FROM preceptors LIMIT 1
)
INSERT INTO subjects (subject_name, teacher, preceptor, course_num, course_letter, course_year)
SELECT 'Matemática I', t.user_id, p.user_id, 1, 'A', '2025'
FROM teacher_id t, preceptor_id p
UNION ALL
SELECT 'Física I', t.user_id, p.user_id, 1, 'A', '2025'
FROM teacher_id t, preceptor_id p
UNION ALL
SELECT 'Programación I', t.user_id, p.user_id, 1, 'A', '2025'
FROM teacher_id t, preceptor_id p;

-- =====================================================
-- VISTAS ÚTILES
-- =====================================================

-- Vista completa de usuarios con información detallada
CREATE OR REPLACE VIEW v_users_complete AS
SELECT 
    u.id,
    u.name,
    u.last_name,
    u.email,
    u.cuil,
    r.name as role_name,
    ui.document_type,
    ui.document_value,
    ui.phone,
    cd.sex,
    cd.birth_date,
    cd.nationality,
    ad.street,
    ad.number,
    ad.locality,
    ad.province
FROM users u
LEFT JOIN roles r ON u.role_id = r.id
LEFT JOIN user_info ui ON u.id = ui.user_id
LEFT JOIN common_data cd ON u.id = cd.user_id
LEFT JOIN address_data ad ON cd.address_data_id = ad.id;

-- Vista de estudiantes con información completa
CREATE OR REPLACE VIEW v_students_complete AS
SELECT 
    s.user_id as student_id,
    s.legajo,
    uc.*
FROM students s
JOIN v_users_complete uc ON s.user_id = uc.id;

-- Vista de materias con información de docentes y preceptores
CREATE OR REPLACE VIEW v_subjects_complete AS
SELECT 
    s.id as subject_id,
    s.subject_name,
    s.course_num,
    s.course_letter,
    s.course_year,
    ut.name as teacher_name,
    ut.last_name as teacher_last_name,
    up.name as preceptor_name,
    up.last_name as preceptor_last_name,
    sc.subject_name as correlative_subject
FROM subjects s
LEFT JOIN users ut ON s.teacher = ut.id
LEFT JOIN users up ON s.preceptor = up.id
LEFT JOIN subjects sc ON s.correlative = sc.id;

-- Vista de inscripciones de estudiantes a materias
CREATE OR REPLACE VIEW v_student_enrollments AS
SELECT 
    ss.id as enrollment_id,
    ss.enrollment_date,
    s.legajo,
    u.name as student_name,
    u.last_name as student_last_name,
    sub.subject_name,
    sub.course_num,
    sub.course_letter,
    sub.course_year
FROM subject_students ss
JOIN students s ON ss.student_id = s.user_id
JOIN users u ON s.user_id = u.id
JOIN subjects sub ON ss.subject_id = sub.id;

-- Vista de resultados de exámenes
CREATE OR REPLACE VIEW v_exam_results_complete AS
SELECT 
    er.id as result_id,
    e.title as exam_title,
    e.date as exam_date,
    e.is_valid,
    sub.subject_name,
    s.legajo,
    u.name as student_name,
    u.last_name as student_last_name,
    er.score
FROM exam_results er
JOIN exams e ON er.exam_id = e.id
JOIN subjects sub ON e.subject_id = sub.id
JOIN students s ON er.student_id = s.user_id
JOIN users u ON s.user_id = u.id;

-- =====================================================
-- FUNCIONES ÚTILES
-- =====================================================

-- Función para contar inasistencias de un estudiante en una materia
-- =====================================================
-- COMENTARIOS FINALES
-- =====================================================

-- Script ejecutado exitosamente
-- Base de datos: dbsiaade
-- Script ejecutado exitosamente
-- Base de datos: dbsiaade
-- Esquema: sistema_roles_v2
-- Tablas creadas: 15 principales + tablas de relaciones
-- Datos iniciales: roles, usuarios de ejemplo, materias base
-- Caracteristicas: UUID para users, SERIAL/INTEGER para otras tablas,
--                  sistema de mesas de examenes
COMMENT ON DATABASE dbsiaade IS 'Sistema Integral de Administracion Academica Educativa - SIAADE v2.0';
