import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoMigration1760135099954 implements MigrationInterface {
    name = 'AutoMigration1760135099954'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "final_exams" DROP CONSTRAINT "FK_dda384e0515ed5b3fb0b63c18e2"`);
        await queryRunner.query(`ALTER TABLE "notices" DROP CONSTRAINT "FK_notices_visible_role"`);
        await queryRunner.query(`ALTER TABLE "notices" DROP CONSTRAINT "FK_notices_created_by"`);
        await queryRunner.query(`DROP INDEX "public"."uq_roles_name_idx"`);
        await queryRunner.query(`DROP INDEX "public"."idx_final_exam_table_created_by"`);
        await queryRunner.query(`CREATE TABLE "academic_period" ("academic_period_id" SERIAL NOT NULL, "period_name" text NOT NULL, "partials_score_needed" smallint, CONSTRAINT "PK_c84fec2739f0343e5930990a8c3" PRIMARY KEY ("academic_period_id"))`);
    await queryRunner.query(`CREATE TABLE "exam_table" ("id" SERIAL NOT NULL, "name" text NOT NULL, "start_date" date NOT NULL, "end_date" date NOT NULL, CONSTRAINT "PK_exam_table_id" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "final_exam_status" ("id" SERIAL NOT NULL, "name" text NOT NULL, CONSTRAINT "UQ_39b4b051ba8a346f6ca54d1ee32" UNIQUE ("name"), CONSTRAINT "PK_a3aa4a16e0cb5e2c87fcd8261f8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "commission" ("id" SERIAL NOT NULL, "commission_letter" text, CONSTRAINT "PK_d108d70411783e2a3a84e386601" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "subject_status_type" ("id" SERIAL NOT NULL, "status_name" character varying NOT NULL, CONSTRAINT "UQ_9d61379e0ce29796ab1f019f199" UNIQUE ("status_name"), CONSTRAINT "PK_b3784b0b05e5f78587a508bcfe1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "subject_commissions" ("id" SERIAL NOT NULL, "subject_id" integer NOT NULL, "commission_id" integer NOT NULL, "teacher_id" uuid NOT NULL, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_e571e9793479304b14d607f6c23" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e7e4849f084c18911c0dbbbc75" ON "subject_commissions" ("teacher_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ad9281a6a38148ce7d9674a2a5" ON "subject_commissions" ("subject_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b3074a12097b0e46d9a53d0aee" ON "subject_commissions" ("subject_id", "commission_id") `);
        await queryRunner.query(`CREATE TABLE "student_subject_progress" ("id" SERIAL NOT NULL, "subject_commission_id" integer NOT NULL, "student_id" uuid NOT NULL, "status_id" integer, "partial_scores" jsonb, "attendance_percentage" numeric(5,2) NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_8dc2e04d76bc60397c20cbe6b34" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5fef2a1967bce469e3d0cfa577" ON "student_subject_progress" ("student_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_553c118da9bf0c4142b4b1920c" ON "student_subject_progress" ("subject_commission_id", "student_id") `);
        await queryRunner.query(`CREATE TABLE "careers" ("id" SERIAL NOT NULL, "career_name" text NOT NULL, "academic_period_id" integer NOT NULL, "preceptor_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_febfc45dc83d58090d3122fde3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "career_students" ("id" SERIAL NOT NULL, "career_id" integer NOT NULL, "student_id" uuid NOT NULL, "enrolled_at" date, CONSTRAINT "PK_6441b6960cf479a4670a3171f33" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "career_subjects" ("id" SERIAL NOT NULL, "career_id" integer NOT NULL, "subject_id" integer NOT NULL, "year_no" smallint, "period_order" smallint, "order_no" integer NOT NULL, CONSTRAINT "PK_aebef84b8a7ca894169a6b50a24" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_120deadc17ec96ea0da3a206c8" ON "career_subjects" ("subject_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0a093df398afe9f019dabba5e8" ON "career_subjects" ("career_id", "order_no") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_687b5fc3eaab5b8a3aa41b0b02" ON "career_subjects" ("career_id", "subject_id") `);
        await queryRunner.query(`CREATE TABLE "subject_prerequisites_by_order" ("id" SERIAL NOT NULL, "career_id" integer NOT NULL, "subject_order_no" integer NOT NULL, "prereq_order_no" integer NOT NULL, CONSTRAINT "PK_a9abf00018f48dbfe485ce11a90" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_50ee4f7f0b189aa1e7c449ef92" ON "subject_prerequisites_by_order" ("career_id", "prereq_order_no") `);
        await queryRunner.query(`CREATE INDEX "IDX_9cf580cc6862fe811d1f706167" ON "subject_prerequisites_by_order" ("career_id", "subject_order_no") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5056193f7e7e31a75f64f82dbe" ON "subject_prerequisites_by_order" ("career_id", "subject_order_no", "prereq_order_no") `);
        await queryRunner.query(`ALTER TABLE "subjects" ADD "academic_period_id" integer`);
        await queryRunner.query(`ALTER TABLE "subjects" ADD "order_no" integer`);
        await queryRunner.query(`ALTER TABLE "subjects" ADD "teacher_formation" text`);
        await queryRunner.query(`ALTER TABLE "subjects" ADD "subject_format" text`);
        await queryRunner.query(`ALTER TABLE "subjects" ADD "annual_workload" text`);
        await queryRunner.query(`ALTER TABLE "subjects" ADD "weekly_workload" text`);
        await queryRunner.query(`ALTER TABLE "final_exams" ADD "exam_table_id" integer`);
        await queryRunner.query(`ALTER TABLE "final_exams_students" ADD "status_id" integer`);
        await queryRunner.query(`ALTER TABLE "final_exams_students" ADD "recorded_by" uuid`);
        await queryRunner.query(`ALTER TABLE "final_exams_students" ADD "recorded_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "final_exams_students" ADD "approved_by" uuid`);
        await queryRunner.query(`ALTER TABLE "final_exams_students" ADD "approved_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "final_exams_students" ADD "final_exam_id" integer`);
        await queryRunner.query(`ALTER TABLE "students" ADD "legajo" text`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "UQ_e8df771e580eb1c9f980d27becc" UNIQUE ("legajo")`);
        await queryRunner.query(`ALTER TABLE "students" ADD "commission" integer`);
        await queryRunner.query(`ALTER TABLE "students" ADD "can_login" boolean`);
        await queryRunner.query(`ALTER TABLE "students" ADD "is_active" boolean`);
        await queryRunner.query(`ALTER TABLE "students" ADD "student_start_year" smallint`);
    await queryRunner.query(`ALTER TABLE "final_exams" ALTER COLUMN "final_exam_table_id" DROP NOT NULL`);
    await queryRunner.query(`ALTER TABLE "final_exams" ALTER COLUMN "exam_date" TYPE TIMESTAMP WITH TIME ZONE USING "exam_date"::timestamptz`);
    await queryRunner.query(`ALTER TABLE "final_exams_students" ALTER COLUMN "enrolled_at" TYPE TIMESTAMP WITH TIME ZONE USING "enrolled_at"::timestamptz`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_65608a94ff5905eb9bbcc3ce75" ON "final_exams_students" ("final_exam_id", "student_id") `);
        await queryRunner.query(`ALTER TABLE "subjects" ADD CONSTRAINT "FK_2e4f2f1f2ddf59ba477a7e531de" FOREIGN KEY ("academic_period_id") REFERENCES "academic_period"("academic_period_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "final_exam_table" ADD CONSTRAINT "FK_cabbdb925276433b87028db9d04" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "final_exams" ADD CONSTRAINT "FK_9a207337ee72ff5885496b2183b" FOREIGN KEY ("final_exam_table_id") REFERENCES "final_exam_table"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "final_exams" ADD CONSTRAINT "FK_dda384e0515ed5b3fb0b63c18e2" FOREIGN KEY ("exam_table_id") REFERENCES "exam_table"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "final_exams_students" ADD CONSTRAINT "FK_61acdc5ce17ac680051378c0584" FOREIGN KEY ("status_id") REFERENCES "final_exam_status"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "final_exams_students" ADD CONSTRAINT "FK_60613f37be9011642ff6a31f88c" FOREIGN KEY ("recorded_by") REFERENCES "teachers"("user_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "final_exams_students" ADD CONSTRAINT "FK_fd8365a5f6fa3355e79ec9d61d4" FOREIGN KEY ("approved_by") REFERENCES "secretaries"("user_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_fb3eff90b11bddf7285f9b4e281" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_d3f279d8d86937741d42867f40f" FOREIGN KEY ("commission") REFERENCES "commission"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subject_commissions" ADD CONSTRAINT "FK_ad9281a6a38148ce7d9674a2a59" FOREIGN KEY ("subject_id") REFERENCES "subjects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subject_commissions" ADD CONSTRAINT "FK_b3b410787bedfa50358315cd538" FOREIGN KEY ("commission_id") REFERENCES "commission"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subject_commissions" ADD CONSTRAINT "FK_e7e4849f084c18911c0dbbbc75a" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("user_id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_subject_progress" ADD CONSTRAINT "FK_f991f9825a87d94bd3a21bd74d8" FOREIGN KEY ("subject_commission_id") REFERENCES "subject_commissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_subject_progress" ADD CONSTRAINT "FK_5fef2a1967bce469e3d0cfa5779" FOREIGN KEY ("student_id") REFERENCES "students"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_subject_progress" ADD CONSTRAINT "FK_bca4f03d4efe3e7b77715ea90b2" FOREIGN KEY ("status_id") REFERENCES "subject_status_type"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notices" ADD CONSTRAINT "FK_8edf397e84eebabdf5e5caae600" FOREIGN KEY ("visible_role_id") REFERENCES "roles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notices" ADD CONSTRAINT "FK_5091560ec8975434a5add94c411" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "careers" ADD CONSTRAINT "FK_c0a16a76beca291e2b89d1717af" FOREIGN KEY ("academic_period_id") REFERENCES "academic_period"("academic_period_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "careers" ADD CONSTRAINT "FK_8fa45f1407e199a5061eb3f4281" FOREIGN KEY ("preceptor_id") REFERENCES "preceptors"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "career_students" ADD CONSTRAINT "FK_3dddb847f5033682c672a973199" FOREIGN KEY ("career_id") REFERENCES "careers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "career_students" ADD CONSTRAINT "FK_f625a148a289aaca8d89da6bb80" FOREIGN KEY ("student_id") REFERENCES "students"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "career_subjects" ADD CONSTRAINT "FK_e3cfafdc32a121a61f4c42de10c" FOREIGN KEY ("career_id") REFERENCES "careers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "career_subjects" ADD CONSTRAINT "FK_120deadc17ec96ea0da3a206c8b" FOREIGN KEY ("subject_id") REFERENCES "subjects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subject_prerequisites_by_order" ADD CONSTRAINT "FK_245ca3fcaecc8a8e25dcae0d08f" FOREIGN KEY ("career_id") REFERENCES "careers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "subject_prerequisites_by_order" DROP CONSTRAINT "FK_245ca3fcaecc8a8e25dcae0d08f"`);
        await queryRunner.query(`ALTER TABLE "career_subjects" DROP CONSTRAINT "FK_120deadc17ec96ea0da3a206c8b"`);
        await queryRunner.query(`ALTER TABLE "career_subjects" DROP CONSTRAINT "FK_e3cfafdc32a121a61f4c42de10c"`);
        await queryRunner.query(`ALTER TABLE "career_students" DROP CONSTRAINT "FK_f625a148a289aaca8d89da6bb80"`);
        await queryRunner.query(`ALTER TABLE "career_students" DROP CONSTRAINT "FK_3dddb847f5033682c672a973199"`);
        await queryRunner.query(`ALTER TABLE "careers" DROP CONSTRAINT "FK_8fa45f1407e199a5061eb3f4281"`);
        await queryRunner.query(`ALTER TABLE "careers" DROP CONSTRAINT "FK_c0a16a76beca291e2b89d1717af"`);
        await queryRunner.query(`ALTER TABLE "notices" DROP CONSTRAINT "FK_5091560ec8975434a5add94c411"`);
        await queryRunner.query(`ALTER TABLE "notices" DROP CONSTRAINT "FK_8edf397e84eebabdf5e5caae600"`);
        await queryRunner.query(`ALTER TABLE "student_subject_progress" DROP CONSTRAINT "FK_bca4f03d4efe3e7b77715ea90b2"`);
        await queryRunner.query(`ALTER TABLE "student_subject_progress" DROP CONSTRAINT "FK_5fef2a1967bce469e3d0cfa5779"`);
        await queryRunner.query(`ALTER TABLE "student_subject_progress" DROP CONSTRAINT "FK_f991f9825a87d94bd3a21bd74d8"`);
        await queryRunner.query(`ALTER TABLE "subject_commissions" DROP CONSTRAINT "FK_e7e4849f084c18911c0dbbbc75a"`);
        await queryRunner.query(`ALTER TABLE "subject_commissions" DROP CONSTRAINT "FK_b3b410787bedfa50358315cd538"`);
        await queryRunner.query(`ALTER TABLE "subject_commissions" DROP CONSTRAINT "FK_ad9281a6a38148ce7d9674a2a59"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_d3f279d8d86937741d42867f40f"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_fb3eff90b11bddf7285f9b4e281"`);
        await queryRunner.query(`ALTER TABLE "final_exams_students" DROP CONSTRAINT "FK_fd8365a5f6fa3355e79ec9d61d4"`);
        await queryRunner.query(`ALTER TABLE "final_exams_students" DROP CONSTRAINT "FK_60613f37be9011642ff6a31f88c"`);
        await queryRunner.query(`ALTER TABLE "final_exams_students" DROP CONSTRAINT "FK_61acdc5ce17ac680051378c0584"`);
        await queryRunner.query(`ALTER TABLE "final_exams" DROP CONSTRAINT "FK_dda384e0515ed5b3fb0b63c18e2"`);
        await queryRunner.query(`ALTER TABLE "final_exams" DROP CONSTRAINT "FK_9a207337ee72ff5885496b2183b"`);
        await queryRunner.query(`ALTER TABLE "final_exam_table" DROP CONSTRAINT "FK_cabbdb925276433b87028db9d04"`);
        await queryRunner.query(`ALTER TABLE "subjects" DROP CONSTRAINT "FK_2e4f2f1f2ddf59ba477a7e531de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_65608a94ff5905eb9bbcc3ce75"`);
    await queryRunner.query(`ALTER TABLE "final_exams_students" ALTER COLUMN "enrolled_at" TYPE date USING "enrolled_at"::date`);
    await queryRunner.query(`ALTER TABLE "final_exams" ALTER COLUMN "exam_date" TYPE date USING "exam_date"::date`);
        await queryRunner.query(`ALTER TABLE "final_exams" ALTER COLUMN "final_exam_table_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "students" DROP COLUMN "student_start_year"`);
        await queryRunner.query(`ALTER TABLE "students" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "students" DROP COLUMN "can_login"`);
        await queryRunner.query(`ALTER TABLE "students" DROP COLUMN "commission"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "UQ_e8df771e580eb1c9f980d27becc"`);
        await queryRunner.query(`ALTER TABLE "students" DROP COLUMN "legajo"`);
        await queryRunner.query(`ALTER TABLE "final_exams_students" DROP COLUMN "final_exam_id"`);
        await queryRunner.query(`ALTER TABLE "final_exams_students" DROP COLUMN "approved_at"`);
        await queryRunner.query(`ALTER TABLE "final_exams_students" DROP COLUMN "approved_by"`);
        await queryRunner.query(`ALTER TABLE "final_exams_students" DROP COLUMN "recorded_at"`);
        await queryRunner.query(`ALTER TABLE "final_exams_students" DROP COLUMN "recorded_by"`);
        await queryRunner.query(`ALTER TABLE "final_exams_students" DROP COLUMN "status_id"`);
        await queryRunner.query(`ALTER TABLE "final_exams" DROP COLUMN "exam_table_id"`);
        await queryRunner.query(`ALTER TABLE "subjects" DROP COLUMN "weekly_workload"`);
        await queryRunner.query(`ALTER TABLE "subjects" DROP COLUMN "annual_workload"`);
        await queryRunner.query(`ALTER TABLE "subjects" DROP COLUMN "subject_format"`);
        await queryRunner.query(`ALTER TABLE "subjects" DROP COLUMN "teacher_formation"`);
        await queryRunner.query(`ALTER TABLE "subjects" DROP COLUMN "order_no"`);
        await queryRunner.query(`ALTER TABLE "subjects" DROP COLUMN "academic_period_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5056193f7e7e31a75f64f82dbe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9cf580cc6862fe811d1f706167"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_50ee4f7f0b189aa1e7c449ef92"`);
        await queryRunner.query(`DROP TABLE "subject_prerequisites_by_order"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_687b5fc3eaab5b8a3aa41b0b02"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0a093df398afe9f019dabba5e8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_120deadc17ec96ea0da3a206c8"`);
        await queryRunner.query(`DROP TABLE "career_subjects"`);
        await queryRunner.query(`DROP TABLE "career_students"`);
        await queryRunner.query(`DROP TABLE "careers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_553c118da9bf0c4142b4b1920c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5fef2a1967bce469e3d0cfa577"`);
        await queryRunner.query(`DROP TABLE "student_subject_progress"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b3074a12097b0e46d9a53d0aee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad9281a6a38148ce7d9674a2a5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e7e4849f084c18911c0dbbbc75"`);
        await queryRunner.query(`DROP TABLE "subject_commissions"`);
        await queryRunner.query(`DROP TABLE "subject_status_type"`);
        await queryRunner.query(`DROP TABLE "commission"`);
        await queryRunner.query(`DROP TABLE "final_exam_status"`);
        await queryRunner.query(`DROP TABLE "exam_table"`);
        await queryRunner.query(`DROP TABLE "academic_period"`);
        await queryRunner.query(`CREATE INDEX "idx_final_exam_table_created_by" ON "final_exam_table" ("created_by") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_roles_name_idx" ON "roles" ("name") `);
        await queryRunner.query(`ALTER TABLE "notices" ADD CONSTRAINT "FK_notices_created_by" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notices" ADD CONSTRAINT "FK_notices_visible_role" FOREIGN KEY ("visible_role_id") REFERENCES "roles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "final_exams" ADD CONSTRAINT "FK_dda384e0515ed5b3fb0b63c18e2" FOREIGN KEY ("final_exam_table_id") REFERENCES "final_exam_table"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
